name: 'Mansion Backend Build'
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version to build'
        required: true

jobs:
  Mansion-Backend:
    name: Mansion-Backend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node modules
      uses: actions/cache@v3
      env:
        cache-name: Mansion-Backend-npm
      with:
        path: ~/.npm
        key: Mansion-Backend-npm
      
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker build
      run: docker build -t sanjail/jack:be-${{ inputs.version }} .
    
    - name: Docker push
      run: docker push sanjail/jack:be-${{ inputs.version }}